---
name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: build DEB Package for Ubuntu
        id: deb_build_ubuntu
        uses: cnangel/build-deb-action@master
        env:
          GITHUB_OUTPUT: "$GITHUB_OUTPUT"
        with:
          buildpackage_opts: --build=binary

      - name: Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release ${{ github.ref_name }}
            - Create DEB and RPM
            - Upload DEB, Source RPM and RPMS
          files: |
            README.md,LICENSE
            ${{ steps.deb_build_ubuntu.outputs.deb_dir_names }}
          token: ${{ secrets.SSE_TOKEN }}
          draft: false
          prerelease: false

#      - name: build RPM Package for CentOS7
#        id: rpm_build_centos7
#        uses: cnangel/rpmbuild@centos7
#        with:
#          spec_file: "cello.spec"
#
#      - name: build RPM Package for CentOS8
#        id: rpm_build_centos8
#        uses: cnangel/rpmbuild@centos8
#        with:
#          spec_file: "cello.spec"
#
#      - name: build RPM Package for CentOS9
#        id: rpm_build_centos9
#        uses: cnangel/rpmbuild@centos9
#        with:
#          spec_file: "cello.spec"
#
#      - name: build RPM Package for Fedora38
#        id: rpm_build_fedora38
#        uses: cnangel/rpmbuild@fedora/38
#        with:
#          spec_file: "cello.spec"
#
#      - name: Release ${{ github.ref_name }}
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: ${{ github.ref }}
#          name: Release ${{ github.ref_name }}
#          body: |
#            Changes in this Release ${{ github.ref_name }}
#            - Create RPM
#            - Upload Source RPM and RPMS
#          files: |
#            README.md,LICENSE
#            ${{ steps.rpm_build_centos7.outputs.rpm_dir_names }}
#            ${{ steps.rpm_build_centos8.outputs.rpm_dir_names }}
#            ${{ steps.rpm_build_centos9.outputs.rpm_dir_names }}
#            ${{ steps.rpm_build_fedora38.outputs.rpm_dir_names }}
#          token: ${{ secrets.SSE_TOKEN }}
#          draft: false
#          prerelease: false
